version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./image_downloader/docker/db/.env

  web:
    build:
      context: .
      dockerfile: ./image_downloader/docker/web/Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    # volumes:
    #   - web_data:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: image_downloader.settings
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./image_downloader/docker/web/.env

volumes:
  postgres_data:
